-- LSP CompletionItemKind 图标
---@type table<string, VVIconEntry>
local M = {
  Text          = { glyph = '', hl = 'MiniIconsGrey' },
  Method        = { glyph = '', hl = 'MiniIconsPurple' },
  Function      = { glyph = '', hl = 'MiniIconsPurple' },
  Constructor   = { glyph = '', hl = 'MiniIconsPurple' },
  Field         = { glyph = '', hl = 'MiniIconsAzure' },
  Variable      = { glyph = '', hl = 'MiniIconsAzure' },
  Property      = { glyph = '', hl = 'MiniIconsAzure' },
  Class         = { glyph = '', hl = 'MiniIconsYellow' },
  Interface     = { glyph = '', hl = 'MiniIconsYellow' },
  Struct        = { glyph = '', hl = 'MiniIconsYellow' },
  Module        = { glyph = '', hl = 'MiniIconsYellow' },
  Namespace     = { glyph = '', hl = 'MiniIconsYellow' },
  Unit          = { glyph = '', hl = 'MiniIconsCyan' },
  Value         = { glyph = '', hl = 'MiniIconsOrange' },
  Enum          = { glyph = '', hl = 'MiniIconsOrange' },
  EnumMember    = { glyph = '', hl = 'MiniIconsOrange' },
  Keyword       = { glyph = '', hl = 'MiniIconsRed' },
  Constant      = { glyph = '', hl = 'MiniIconsOrange' },
  Snippet       = { glyph = '', hl = 'MiniIconsCyan' },
  Color         = { glyph = '', hl = 'MiniIconsPurple' },
  File          = { glyph = '', hl = 'MiniIconsBlue' },
  Folder        = { glyph = '', hl = 'MiniIconsBlue' },
  Reference     = { glyph = '', hl = 'MiniIconsCyan' },
  Event         = { glyph = '', hl = 'MiniIconsOrange' },
  Operator      = { glyph = '', hl = 'MiniIconsRed' },
  TypeParameter = { glyph = '', hl = 'MiniIconsPurple' },
  Array         = { glyph = '', hl = 'MiniIconsOrange' },
  Boolean       = { glyph = '', hl = 'MiniIconsOrange' },
  Collapsed     = { glyph = '', hl = 'MiniIconsGrey' },
  Control       = { glyph = '', hl = 'MiniIconsPurple' },
  Key           = { glyph = '', hl = 'MiniIconsYellow' },
  Null          = { glyph = '', hl = 'MiniIconsGrey' },
  Number        = { glyph = '', hl = 'MiniIconsOrange' },
  Object        = { glyph = '', hl = 'MiniIconsYellow' },
  Package       = { glyph = '', hl = 'MiniIconsRed' },
  String        = { glyph = '', hl = 'MiniIconsGreen' },
  Supermaven    = { glyph = '󱐗', hl = 'MiniIconsGreen' },
}

return M
